#! /bin/sh

sxhkd &

${HOME}/.config/polybar/launch.sh &

# bspc monitor -d 1 2 3 4 5 6 7 8 9
bspc monitor HDMI-A-0 -d 1 2 3 4 5
bspc monitor HDMI-A-1 -d 6 7 8 9 0

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config normal_border_color "#000000"
bspc config focused_border_color "#272c31"

bspc config border_width 0
bspc config window_gap 8

bspc config focus_follows_pointer false

bspc config split_ratio      0.50
bspc config initial_polarity first_child

bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config single_monocle	true

bspc rule -a Telegram-desktop state=floating follow=on
bspc rule -a Pavucotrol state=floating follow=on
bspc rule -a Screenkey manage=off
